# ---- APARIENCIA ----
# Si usas el kitten de temas, esto se gestiona solo al final del archivo
# include themes/Sakura-Night.conf

font_family      JetBrainsMono Nerd Font
font_size        12.5
background_opacity 0.85
dynamic_background_opacity yes

# ---- VENTANA (Ajustado para Sway) ----
window_padding_width 10
hide_window_decorations yes
confirm_os_window_close 0

# ---- CURSOR ----
cursor_shape beam
cursor_beam_thickness 2.0
cursor_blink_interval 0.25
# Permitir integración pero mantener nuestro estilo de cursor
shell_integration enabled
cursor_stop_blinking_after 3
enable_audio_bell no

#-----------------


# ---- DESEMPEÑO ----
# Mejora el input lag en monitores de alta tasa de refresco
repaint_delay 8
input_delay 2
sync_to_monitor yes

# ---- KEYBINDS EXTRAS ----
# Abrir nueva terminal en el MISMO directorio (Muy útil para dotfiles)
map ctrl+shift+enter launch --cwd=current --type=os-window

# ---- TABS ESTILO POWERLINE ----
tab_bar_edge bottom
tab_bar_style powerline
tab_powerline_style slanted
active_tab_font_style bold

# BEGIN_KITTY_THEME
# Cyberpunk Neon
include current-theme.conf
# END_KITTY_THEME
