-- ###############################################################################
-- #                         JAVIER HYPRLAND CONFIG (LUA)                        #
-- ###############################################################################
-- Sintaxis nueva: Hyprland 0.55+ con API Lua oficial

hl.config({ autogenerated = false })

-- =============================================================================
-- 1. RUTAS Y VARIABLES
-- =============================================================================
local mod = "SUPER"
local wall = "/home/javier/dotfiles/.config/hypr/wallpapers/957277.jpg"
local hp_config = "/home/javier/dotfiles/.config/hypr/hyprpaper.conf"

-- =============================================================================
-- 2. MONITOR
-- =============================================================================
hl.monitor({
    output   = "",
    mode     = "preferred",
    position = "auto",
    scale    = 1.25,
})

-- =============================================================================
-- 3. AUTOSTART
-- =============================================================================
hl.on("hyprland.start", function()
    hl.exec_cmd("waybar -c /home/javier/dotfiles/.config/waybar/waybar-hyprl/config -s /home/javier/dotfiles/.config/waybar/waybar-hyprl/style.css")
    hl.exec_cmd("swaync")
    hl.exec_cmd("hyprpaper -c " .. hp_config)
    hl.exec_cmd("hyprctl hyprpaper wallpaper ', " .. wall .. "'")
    hl.exec_cmd("gsettings set org.gnome.desktop.interface gtk-theme 'Dream-Violet-Dark-GTK'")
    hl.exec_cmd("gsettings set org.gnome.desktop.interface icon-theme 'Papirus-Dark'")
end)

-- =============================================================================
-- 4. CONFIGURACIÓN GENERAL Y ANIMACIONES
-- =============================================================================
hl.config({
    general = {
        gaps_in     = 10,
        gaps_out    = 4,
        border_size = 4,
        col = {
            active_border   = { colors = { "rgba(bf00ffff)", "rgba(4b0082ff)" }, angle = 45 },
            inactive_border = "rgba(2a2a2aff)",
        },
        layout = "dwindle",
    },
	gestures = {
        workspace_swipe = true,
        workspace_swipe_fingers = 3,
        workspace_swipe_distance = 300,
        workspace_swipe_invert = true, -- true = movimiento natural (estilo MacOS/Sway)
        workspace_swipe_min_speed_to_force = 30,
        workspace_swipe_cancel_ratio = 0.5,
    },

    -- SECCIÓN DE ANIMACIONES RÁPIDAS
    animations = {
        enabled = true,
        bezier = { "overshot", 0.05, 0.9, 0.1, 1.05 },
        animation = {
            { "windows",     true, 3, "overshot" },            -- Ventanas rápidas
            { "windowsOut",  true, 3, "overshot", "popin 80%" },-- Salida con encogimiento
            { "border",      true, 2, "default" },             -- Borde muy rápido
            { "fade",        true, 3, "default" },             -- Desvanecimiento ágil
            { "workspaces",  true, 3, "overshot", "slide" },   -- Deslizamiento de escritorios
        },
    },

    decoration = {
        rounding = 10,
        shadow = {
            enabled      = true,
            range        = 4,
            render_power = 3,
            color        = "rgba(1a1a2eff)",
        },
    },

    input = {
        kb_layout = "es,latam",
        follow_mouse = 1,
        touchpad = {
            natural_scroll = true,
            tap_to_click   = true,
        },
    },

    dwindle = {
        preserve_split = true,
    },

    misc = {
        force_default_wallpaper = -1,
        disable_hyprland_logo   = false,
    },
})

-- =============================================================================
-- 5. KEYBINDS
-- =============================================================================

-- Aplicaciones
hl.bind(mod .. " + RETURN", hl.dsp.exec_cmd("kitty"))
hl.bind(mod .. " + D",      hl.dsp.exec_cmd("rofi -show drun"))
hl.bind(mod .. " + T",      hl.dsp.exec_cmd("thunar"))
hl.bind(mod .. " + B",      hl.dsp.exec_cmd("brave-browser"))
hl.bind(mod .. " + SHIFT + N", hl.dsp.exec_cmd("swaync-client -t -sw"))

-- Gestión de sesión
hl.bind(mod .. " + SHIFT + Q", hl.dsp.window.close())
hl.bind(mod .. " + SHIFT + W", hl.dsp.exec_cmd("wlogout -b 6"))
hl.bind(mod .. " + ESCAPE",    hl.dsp.exec_cmd("swaylock -f -i " .. wall))

-- Cambio de foco (flechas)
hl.bind(mod .. " + left",  hl.dsp.focus({ direction = "left" }))
hl.bind(mod .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mod .. " + up",    hl.dsp.focus({ direction = "up" }))
hl.bind(mod .. " + down",  hl.dsp.focus({ direction = "down" }))

-- Mover ventanas (flechas)
hl.bind(mod .. " + SHIFT + left",  hl.dsp.window.move({ direction = "left" }))
hl.bind(mod .. " + SHIFT + right", hl.dsp.window.move({ direction = "right" }))
hl.bind(mod .. " + SHIFT + up",    hl.dsp.window.move({ direction = "up" }))
hl.bind(mod .. " + SHIFT + down",  hl.dsp.window.move({ direction = "down" }))

-- Workspaces 1-10
for i = 1, 10 do
    local key = i % 10
    hl.bind(mod .. " + " .. key,           hl.dsp.focus({ workspace = i }))
    hl.bind(mod .. " + SHIFT + " .. key,   hl.dsp.window.move({ workspace = i }))
end

-- Navegación entre workspaces (Ctrl + Super + Flechas)
hl.bind(mod .. " + CONTROL + left",  hl.dsp.focus({ workspace = "e-1" }))
hl.bind(mod .. " + CONTROL + right", hl.dsp.focus({ workspace = "e+1" }))
